# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.DateField(blank=True, null=True),
        ),
    ]
